#define PCI_DEV_HAS_SUPPORTED_ME_FROM_KERNEL(x) ( \
    ((x) ==  MEI_DEV_ID_82G35) || \
    ((x) ==  MEI_DEV_ID_82Q965) || \
    ((x) ==  MEI_DEV_ID_82G965) || \
    ((x) ==  MEI_DEV_ID_82GM965) || \
    ((x) ==  MEI_DEV_ID_82GME965) || \
    ((x) ==  MEI_DEV_ID_ICH9_82Q35) || \
    ((x) ==  MEI_DEV_ID_ICH9_82G33) || \
    ((x) ==  MEI_DEV_ID_ICH9_82Q33) || \
    ((x) ==  MEI_DEV_ID_ICH9_82X38) || \
    ((x) ==  MEI_DEV_ID_ICH9_3200) || \
    ((x) ==  MEI_DEV_ID_ICH9_6) || \
    ((x) ==  MEI_DEV_ID_ICH9_7) || \
    ((x) ==  MEI_DEV_ID_ICH9_8) || \
    ((x) ==  MEI_DEV_ID_ICH9_9) || \
    ((x) ==  MEI_DEV_ID_ICH9_10) || \
    ((x) ==  MEI_DEV_ID_ICH9M_1) || \
    ((x) ==  MEI_DEV_ID_ICH9M_2) || \
    ((x) ==  MEI_DEV_ID_ICH9M_3) || \
    ((x) ==  MEI_DEV_ID_ICH9M_4) || \
    ((x) ==  MEI_DEV_ID_ICH10_1) || \
    ((x) ==  MEI_DEV_ID_ICH10_2) || \
    ((x) ==  MEI_DEV_ID_ICH10_3) || \
    ((x) ==  MEI_DEV_ID_ICH10_4) || \
    ((x) ==  MEI_DEV_ID_IBXPK_1) || \
    ((x) ==  MEI_DEV_ID_IBXPK_2) || \
    ((x) ==  MEI_DEV_ID_CPT_1) || \
    ((x) ==  MEI_DEV_ID_PBG_1) || \
    ((x) ==  MEI_DEV_ID_PPT_1) || \
    ((x) ==  MEI_DEV_ID_PPT_2) || \
    ((x) ==  MEI_DEV_ID_PPT_3) || \
    ((x) ==  MEI_DEV_ID_LPT_H) || \
    ((x) ==  MEI_DEV_ID_LPT_W) || \
    ((x) ==  MEI_DEV_ID_LPT_LP) || \
    ((x) ==  MEI_DEV_ID_LPT_HR) || \
    ((x) ==  MEI_DEV_ID_WPT_LP) || \
    ((x) ==  MEI_DEV_ID_WPT_LP_2) || \
    ((x) ==  MEI_DEV_ID_SPT) || \
    ((x) ==  MEI_DEV_ID_SPT_2) || \
    ((x) ==  MEI_DEV_ID_SPT_3) || \
    ((x) ==  MEI_DEV_ID_SPT_H) || \
    ((x) ==  MEI_DEV_ID_SPT_H_2) || \
    ((x) ==  MEI_DEV_ID_LBG) || \
    ((x) ==  MEI_DEV_ID_BXT_M) || \
    ((x) ==  MEI_DEV_ID_APL_I) || \
    ((x) ==  MEI_DEV_ID_DNV_IE) || \
    ((x) ==  MEI_DEV_ID_GLK) || \
    ((x) ==  MEI_DEV_ID_KBP) || \
    ((x) ==  MEI_DEV_ID_KBP_2) || \
    ((x) ==  MEI_DEV_ID_KBP_3) || \
    ((x) ==  MEI_DEV_ID_CNP_LP) || \
    ((x) ==  MEI_DEV_ID_CNP_LP_3) || \
    ((x) ==  MEI_DEV_ID_CNP_H) || \
    ((x) ==  MEI_DEV_ID_CNP_H_3) || \
    ((x) ==  MEI_DEV_ID_CMP_LP) || \
    ((x) ==  MEI_DEV_ID_CMP_LP_3) || \
    ((x) ==  MEI_DEV_ID_CMP_V) || \
    ((x) ==  MEI_DEV_ID_CMP_H) || \
    ((x) ==  MEI_DEV_ID_CMP_H_3) || \
    ((x) ==  MEI_DEV_ID_CDF) || \
    ((x) ==  MEI_DEV_ID_ICP_LP) || \
    ((x) ==  MEI_DEV_ID_JSP_N) || \
    ((x) ==  MEI_DEV_ID_TGP_LP) || \
    ((x) ==  MEI_DEV_ID_TGP_H) || \
    ((x) ==  MEI_DEV_ID_MCC) || \
    ((x) ==  MEI_DEV_ID_MCC_4) || \
    ((x) ==  MEI_DEV_ID_EBG) || \
    ((x) ==  MEI_DEV_ID_ADP_S) || \
    ((x) ==  MEI_DEV_ID_ADP_LP) || \
    ((x) ==  MEI_DEV_ID_ADP_P) || \
0)
